.PHONY: all clean help

CFLAGS=-Wall -g -w

all:
	cc -o ex1 ex1.c

clean:
	rm -f ex1

help:
	$(info )
	$(info ************ MAKE HELP **********)
	$(info * all - compile without input)
	$(info * clean - remove executable file)
